version: '3.8'

services:
  llama-server-vulkan:
    image: ghcr.io/kth8/llama-server-vulkan
    container_name: llama-server-vulkan
    ports:
      - "8001:8080"
    init: true
    devices:
      - /dev/kfd
      - /dev/dri
    labels:
      io.containers.autoupdate: registry

