version: "3.8"
services:
  llama-server-vulkan:
    image: ghcr.io/kth8/llama-server-vulkan
    container_name: llama-server-vulkan
    init: true
    labels:
      - "io.containers.autoupdate=registry"
    ports:
      - "8001:8080"
    devices:
      - /dev/kfd
      - /dev/dri
